### ISSUE TITLE
java.lang.NegativeArraySizeException while working on Raspberry Pi 3

### ISSUE THREAD

**Issue by lsahn-gh** [OpenWinCon/OpenWinNet#1]
OS : raspbian latest
Kernel : 4.4.50
Network setting : wlan1 dev is already connected in a 공유기

ifconfig 
```
wlan1     Link encap:Ethernet  HWaddr 30:b5:c2:06:c8:3e  
          inet addr:172.30.1.39  Bcast:172.30.1.255  Mask:255.255.255.0
          inet6 addr: fe80::44d5:b90a:21b7:3301/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:909 errors:0 dropped:312 overruns:0 frame:0
          TX packets:157 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:234150 (228.6 KiB)  TX bytes:28748 (28.0 KiB)
```
Command to run is that : sudo java -jar GOTHAM_hazel.jar wlan1 1 10.0.0.10
```
pi@raspberrypi:~/Fun5G/Mesh/GOTHAM(vis)/settingFile/dist $ sudo java -jar GOTHAM_hazel.jar eth0 1 10.0.0.10
eth0      Link encap:Ethernet  HWaddr b8:27:eb:16:b2:c8  
          inet addr:192.168.0.112  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::bba:2bd6:23c2:efe7/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:42220 errors:0 dropped:3827 overruns:0 frame:0
          TX packets:17860 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:48173150 (45.9 MiB)  TX bytes:1777641 (1.6 MiB)

b8:27:eb:16:b2:c8
Apr 26, 2017 3:09:14 PM com.hazelcast.instance.DefaultAddressPicker
INFO: [LOCAL] [dev] [3.6.4] Prefer IPv4 stack is true.
Apr 26, 2017 3:09:14 PM com.hazelcast.instance.DefaultAddressPicker
INFO: [LOCAL] [dev] [3.6.4] Picked Address[172.30.1.39]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true
Apr 26, 2017 3:09:14 PM com.hazelcast.system
INFO: [172.30.1.39]:5701 [dev] [3.6.4] Hazelcast 3.6.4 (20160701 - 5b94d9f) starting at Address[172.30.1.39]:5701
Apr 26, 2017 3:09:14 PM com.hazelcast.system
INFO: [172.30.1.39]:5701 [dev] [3.6.4] Copyright (c) 2008-2016, Hazelcast, Inc. All Rights Reserved.
Apr 26, 2017 3:09:14 PM com.hazelcast.system
INFO: [172.30.1.39]:5701 [dev] [3.6.4] Configured Hazelcast Serialization version : 1
Apr 26, 2017 3:09:15 PM com.hazelcast.nio.UnsafeHelper
WARNING: sun.misc.Unsafe has been disabled because your platform does not support unaligned access to memory, some features might be not available.
Apr 26, 2017 3:09:15 PM com.hazelcast.spi.OperationService
INFO: [172.30.1.39]:5701 [dev] [3.6.4] Backpressure is disabled
Apr 26, 2017 3:09:15 PM com.hazelcast.spi.impl.operationexecutor.classic.ClassicOperationExecutor
INFO: [172.30.1.39]:5701 [dev] [3.6.4] Starting with 2 generic operation threads and 4 partition operation threads.
Apr 26, 2017 3:09:16 PM com.hazelcast.instance.Node
INFO: [172.30.1.39]:5701 [dev] [3.6.4] Creating MulticastJoiner
Apr 26, 2017 3:09:17 PM com.hazelcast.core.LifecycleService
INFO: [172.30.1.39]:5701 [dev] [3.6.4] Address[172.30.1.39]:5701 is STARTING
Apr 26, 2017 3:09:17 PM com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThreadingModel
INFO: [172.30.1.39]:5701 [dev] [3.6.4] TcpIpConnectionManager configured with Non Blocking IO-threading model: 3 input threads and 3 output threads
Apr 26, 2017 3:09:20 PM com.hazelcast.cluster.impl.MulticastJoiner
INFO: [172.30.1.39]:5701 [dev] [3.6.4] 


Members [1] {
	Member [172.30.1.39]:5701 this
}

Apr 26, 2017 3:09:20 PM com.hazelcast.core.LifecycleService
INFO: [172.30.1.39]:5701 [dev] [3.6.4] Address[172.30.1.39]:5701 is STARTED
Apr 26, 2017 3:09:20 PM com.hazelcast.partition.InternalPartitionService
INFO: [172.30.1.39]:5701 [dev] [3.6.4] Initializing cluster partition table arrangement...
finish matrix starter
before update
start updateStatus
waiting web client
Exception in thread "main" java.lang.NegativeArraySizeException
	at gotham_hazel.Update.updateStatus(Update.java:92)
	at gotham_hazel.Update.<init>(Update.java:40)
	at gotham_hazel.GOTHAM_hazel.main(GOTHAM_hazel.java:42)
```

as above, the error **java.lang.NegativeArraySizeException** has been raised.
Would you please help me to solve this one?

Thank you for this and paper about G.O.T.H.A.M.
they are so impressive :)

**Comment by BetaS** [comment]
Hello!
Thanks for your reporting.

For detail information, could you embed full text of `batctl o` command?
 (note: it should be run as 'root')
